language: java                                               
jdk:                           
    - oraclejdk8                                               
after_success:
    - mvn -B -V jacoco:report coveralls:report
